# Netlify.toml reference https://www.netlify.com/docs/netlify-toml-reference/

# Node version is set by .nvmrc
[build]
    base = "/"
    command = "npm run build"
    publish = "public"

# anything special that needs to be set in prod
[context.production.environment]
    GATSBY_ENV = "prod"

# anything special that needs to be set in branch deploys
[context.develop.environment]
    GATSBY_ENV = "dev"

